version: '3.8'

services:
  nginx-server:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:8080"
      - "8081:8081"

  tester:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - nginx-server
