name: Docker Compose CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Test with Docker Compose
        run: |
          docker-compose up --build --abort-on-container-exit
          if [ $? -eq 0 ]; then
            echo "Test succeeded" > succeeded
          else
            echo "Test failed" > fail
          fi

      - name: Upload result artifact
        uses: actions/upload-artifact@v2
        with:
          name: result
          path: succeeded
